# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from Apps.uav_simulator.simulator.communication.grpc import communication_service_pb2 as communication__service__pb2


class CommunicationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StatusUpdateRequest = channel.unary_unary(
                '/communication_service.CommunicationService/StatusUpdateRequest',
                request_serializer=communication__service__pb2.pStatusUpdate.SerializeToString,
                response_deserializer=communication__service__pb2.pResponse.FromString,
                )
        self.FlyToDestinationRequest = channel.unary_unary(
                '/communication_service.CommunicationService/FlyToDestinationRequest',
                request_serializer=communication__service__pb2.pFlyToDestination.SerializeToString,
                response_deserializer=communication__service__pb2.pResponse.FromString,
                )


class CommunicationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StatusUpdateRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FlyToDestinationRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommunicationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StatusUpdateRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.StatusUpdateRequest,
                    request_deserializer=communication__service__pb2.pStatusUpdate.FromString,
                    response_serializer=communication__service__pb2.pResponse.SerializeToString,
            ),
            'FlyToDestinationRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.FlyToDestinationRequest,
                    request_deserializer=communication__service__pb2.pFlyToDestination.FromString,
                    response_serializer=communication__service__pb2.pResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'communication_service.CommunicationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CommunicationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StatusUpdateRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/communication_service.CommunicationService/StatusUpdateRequest',
            communication__service__pb2.pStatusUpdate.SerializeToString,
            communication__service__pb2.pResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FlyToDestinationRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/communication_service.CommunicationService/FlyToDestinationRequest',
            communication__service__pb2.pFlyToDestination.SerializeToString,
            communication__service__pb2.pResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
